services:
  app:
    build: .
    image: kouserdev/banking-app:latest
    ports:
      - "80:80"
    environment:
      - JWT_SECRET=supersecret
    volumes:
      - banking-data:/app/data

volumes:
  banking-data: