[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true

[program:backend]
command=node /app/backend/server.js
autostart=true
autorestart=true
environment=PORT="5000",JWT_SECRET="%(ENV_JWT_SECRET)s"
stdout_logfile=/var/log/backend.log
stderr_logfile=/var/log/backend_err.log